export const dataset = [
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Jan',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Feb',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Mar',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Apr',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'May',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'June',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'July',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Aug',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Sept',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Oct',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Nov',
  },
  {
    DailyClockIn: 59,
    MondayMeeting: 57,
    WorkdoneEmail: 86,
    DailyClockOut: 21,
    month: 'Dec',
  },
];
