-- AlterTable
ALTER TABLE `organisation_user_position` MODIFY `user_position` ENUM('FULL_STACK_DEVELOPER', 'POWER_BI_DEVELOPER', 'SALES', 'HUMAN_RESOURCE', 'TESTING', 'SALESFORCE', 'ADMIN') NOT NULL;

-- AlterTable
ALTER TABLE `tags` MODIFY `user_position` ENUM('FULL_STACK_DEVELOPER', 'POWER_BI_DEVELOPER', 'SALES', 'HUMAN_RESOURCE', 'TESTING', 'SALESFORCE', 'ADMIN') NOT NULL;
